### ISSUE TITLE
Map 并发读写

### ISSUE THREAD

**Issue by lenghan1991** [zouyx/agollo#88]
**Agollo 版本 :**
 - Version [2.2.4]

**日志信息**
fatal error: concurrent map iteration and map write

goroutine 44 [running]:
runtime.throw(0x4fc30e1, 0x26)
	/Users/han/.gvm/gos/go1.12.4/src/runtime/panic.go:617 +0x72 fp=0xc0000f3df0 sp=0xc0000f3dc0 pc=0x402ff52
runtime.mapiternext(0xc0000f3f10)
	/Users/han/.gvm/gos/go1.12.4/src/runtime/map.go:860 +0x597 fp=0xc0000f3e78 sp=0xc0000f3df0 pc=0x4011917
runtime.mapiterinit(0x4dba0e0, 0xc0001dd170, 0xc0000f3f10)
	/Users/han/.gvm/gos/go1.12.4/src/runtime/map.go:850 +0x1c9 fp=0xc0000f3e98 sp=0xc0000f3e78 pc=0x4011289
github.com/zouyx/agollo/v2.autoSyncNamespaceConfigServices(0x0, 0xc0001dd170, 0x4, 0xc000159a80)
	/Users/han/GOPATH/pkg/mod/github.com/zouyx/agollo/v2@v2.2.4/componet_notify.go:229 +0x95 fp=0xc0000f3f80 sp=0xc0000f3e98 pc=0x4457be5
github.com/zouyx/agollo/v2.autoSyncConfigServices(...)
	/Users/han/GOPATH/pkg/mod/github.com/zouyx/agollo/v2@v2.2.4/componet_notify.go:219
github.com/zouyx/agollo/v2.notifySyncConfigServices(0xc0001dd1a0, 0xc000150330)
	/Users/han/GOPATH/pkg/mod/github.com/zouyx/agollo/v2@v2.2.4/componet_notify.go:122 +0x9d fp=0xc0000f3fd0 sp=0xc0000f3f80 pc=0x44572bd
runtime.goexit()
	/Users/han/.gvm/gos/go1.12.4/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc0000f3fd8 sp=0xc0000f3fd0 pc=0x405f8f1
created by github.com/zouyx/agollo/v2.startAgollo
	/Users/han/GOPATH/pkg/mod/github.com/zouyx/agollo/v2@v2.2.4/start.go:63 +0x51

**其他上下文**
关闭缓存文件，`IsBackupConfig: false`

**Comment by qiluge** [comment]
一样的问题，我记得你之前修过，怎么又有了？ @zouyx

**Comment by zouyx** [comment]
十分感谢两位的反馈，我尝试了一下没有重现该问题，你们能帮忙看看我这个demo和你们的场景有什么分别吗？[demo](https://github.com/zouyx/agollo_demo)

 @qiluge 如果是楼主反馈的问题应该是新加标记引起，但具体我没看到是什么代码引起。

**Comment by lenghan1991** [comment]
@zouyx 也可能是之前就有的问题，我没稳定复现。现在只是调整配置的时候出现过。

**Comment by zouyx** [comment]
@lenghan1991 好的，我再测试下，那你现在可以避免吗？或者你把能重现问题的app。properties，脱敏后给我一份

**Comment by qiluge** [comment]
我遇到的是偶发性的问题，下面是panic信息
```
GOROOT=F:\Go #gosetup
GOPATH=F:\code #gosetup
F:\Go\bin\go.exe build -o C:\Users\92144\AppData\Local\Temp\___eth.exe git.ont.io/waas/walletsvr-eth #gosetup
C:\Users\92144\AppData\Local\Temp\___eth.exe -p 123456 #gosetup
fatal error: concurrent map writes

goroutine 42 [running]:
runtime.throw(0x12b22f7, 0x15)
	F:/Go/src/runtime/panic.go:617 +0x79 fp=0xc000349be0 sp=0xc000349bb0 pc=0x4324d9
runtime.mapassign_faststr(0x11129c0, 0xc0002b0690, 0xc00034002f, 0xf, 0x1dd7f80)
	F:/Go/src/runtime/map_faststr.go:211 +0x431 fp=0xc000349c48 sp=0xc000349be0 pc=0x414ff1
github.com/zouyx/agollo/v2.createNamespaceConfig.func1(0xc00034002f, 0xf)
	F:/code/pkg/mod/github.com/zouyx/agollo/v2@v2.2.4/repository.go:85 +0x155 fp=0xc000349c90 sp=0xc000349c48 pc=0xa7a415
github.com/zouyx/agollo/v2.splitNamespaces(0xc00034002f, 0xf, 0xc000349d38, 0x0)
	F:/code/pkg/mod/github.com/zouyx/agollo/v2@v2.2.4/component_common.go:38 +0xde fp=0xc000349d18 sp=0xc000349c90 pc=0xa73dde
github.com/zouyx/agollo/v2.createNamespaceConfig(0x1dd6020, 0xc00034002f, 0xf)
	F:/code/pkg/mod/github.com/zouyx/agollo/v2@v2.2.4/repository.go:75 +0x64 fp=0xc000349d58 sp=0xc000349d18 pc=0xa76874
github.com/zouyx/agollo/v2.initNamespaceConfig(0xc00034002f, 0xf)
	F:/code/pkg/mod/github.com/zouyx/agollo/v2@v2.2.4/repository.go:61 +0x48 fp=0xc000349d80 sp=0xc000349d58 pc=0xa766e8
github.com/zouyx/agollo/v2.GetConfigAndInit(0xc00034002f, 0xf, 0x0)
	F:/code/pkg/mod/github.com/zouyx/agollo/v2@v2.2.4/repository.go:198 +0xcb fp=0xc000349db8 sp=0xc000349d80 pc=0xa775fb
github.com/zouyx/agollo/v2.GetConfig(...)
	F:/code/pkg/mod/github.com/zouyx/agollo/v2@v2.2.4/repository.go:188
github.com/zouyx/agollo/v2.updateApolloConfigCache(0x0, 0x78, 0xc00034002f, 0xf, 0x0)
	F:/code/pkg/mod/github.com/zouyx/agollo/v2@v2.2.4/repository.go:255 +0x64 fp=0xc000349f70 sp=0xc000349db8 pc=0xa77954
github.com/zouyx/agollo/v2.updateApolloConfig(0xc0002506c0, 0x0)
	F:/code/pkg/mod/github.com/zouyx/agollo/v2@v2.2.4/repository.go:232 +0x5e fp=0xc000349fd0 sp=0xc000349f70 pc=0xa7769e
runtime.goexit()
	F:/Go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000349fd8 sp=0xc000349fd0 pc=0x460271
created by github.com/zouyx/agollo/v2.initApolloConfigCache.func1.1
	F:/code/pkg/mod/github.com/zouyx/agollo/v2@v2.2.4/app_config.go:165 +0xbd

goroutine 1 [runnable, locked to thread]:
github.com/zouyx/agollo/v2.createNamespaceConfig(0x1dd6020, 0xc000340000, 0xaa)
	F:/code/pkg/mod/github.com/zouyx/agollo/v2@v2.2.4/repository.go:74 +0x73
github.com/zouyx/agollo/v2.initConfigCache(0x1dd6020)
	F:/code/pkg/mod/github.com/zouyx/agollo/v2@v2.2.4/repository.go:71 +0xdc
github.com/zouyx/agollo/v2.initDefaultConfig(...)
	F:/code/pkg/mod/github.com/zouyx/agollo/v2@v2.2.4/repository.go:55
github.com/zouyx/agollo/v2.initCommon()
	F:/code/pkg/mod/github.com/zouyx/agollo/v2@v2.2.4/start.go:15 +0x35
github.com/zouyx/agollo/v2.init.3()
	F:/code/pkg/mod/github.com/zouyx/agollo/v2@v2.2.4/start.go:11 +0x37

goroutine 4 [chan receive]:
github.com/bilibili/kratos/pkg/stat/sys/cpu.init.0.func1()
	F:/code/pkg/mod/github.com/ontspace/kratos@v0.3.0/pkg/stat/sys/cpu/cpu.go:40 +0x7a
created by github.com/bilibili/kratos/pkg/stat/sys/cpu.init.0
	F:/code/pkg/mod/github.com/ontspace/kratos@v0.3.0/pkg/stat/sys/cpu/cpu.go:36 +0x7a

goroutine 5 [chan receive]:
github.com/bilibili/kratos/pkg/ratelimit/bbr.cpuproc()
	F:/code/pkg/mod/github.com/ontspace/kratos@v0.3.0/pkg/ratelimit/bbr/bbr.go:47 +0xbf
created by github.com/bilibili/kratos/pkg/ratelimit/bbr.init.0
	F:/code/pkg/mod/github.com/ontspace/kratos@v0.3.0/pkg/ratelimit/bbr/bbr.go:32 +0x3c

goroutine 39 [runnable]:
github.com/zouyx/agollo/v2.updateApolloConfig(0xc0002505a0, 0x0)
	F:/code/pkg/mod/github.com/zouyx/agollo/v2@v2.2.4/repository.go:226
created by github.com/zouyx/agollo/v2.initApolloConfigCache.func1.1
	F:/code/pkg/mod/github.com/zouyx/agollo/v2@v2.2.4/app_config.go:165 +0xbd

goroutine 40 [runnable]:
github.com/zouyx/agollo/v2.(*notificationsMap).getNotifies(0xc000004400, 0xc00034000c, 0xd, 0x0, 0x0)
	F:/code/pkg/mod/github.com/zouyx/agollo/v2@v2.2.4/componet_notify.go:66 +0x291
github.com/zouyx/agollo/v2.notifyRemoteConfig(0x0, 0xc00034000c, 0xd, 0x11c6b40, 0xc000261ce0, 0x40da23, 0xc000004400, 0x20)
	F:/code/pkg/mod/github.com/zouyx/agollo/v2@v2.2.4/componet_notify.go:171 +0x72
github.com/zouyx/agollo/v2.notifySimpleSyncConfigServices(0xc00034000c, 0xd, 0xc00034000c, 0xd)
	F:/code/pkg/mod/github.com/zouyx/agollo/v2@v2.2.4/componet_notify.go:139 +0x60
github.com/zouyx/agollo/v2.GetConfigAndInit(0xc00034000c, 0xd, 0x0)
	F:/code/pkg/mod/github.com/zouyx/agollo/v2@v2.2.4/repository.go:200 +0xe3
github.com/zouyx/agollo/v2.GetConfig(...)
	F:/code/pkg/mod/github.com/zouyx/agollo/v2@v2.2.4/repository.go:188
github.com/zouyx/agollo/v2.updateApolloConfigCache(0x0, 0x78, 0xc00034000c, 0xd, 0x0)
	F:/code/pkg/mod/github.com/zouyx/agollo/v2@v2.2.4/repository.go:255 +0x64
github.com/zouyx/agollo/v2.updateApolloConfig(0xc000250600, 0x0)
	F:/code/pkg/mod/github.com/zouyx/agollo/v2@v2.2.4/repository.go:232 +0x5e
created by github.com/zouyx/agollo/v2.initApolloConfigCache.func1.1
	F:/code/pkg/mod/github.com/zouyx/agollo/v2@v2.2.4/app_config.go:165 +0xbd

goroutine 41 [runnable]:
github.com/zouyx/agollo/v2.updateApolloConfig(0xc000250660, 0x0)
	F:/code/pkg/mod/github.com/zouyx/agollo/v2@v2.2.4/repository.go:226
created by github.com/zouyx/agollo/v2.initApolloConfigCache.func1.1
	F:/code/pkg/mod/github.com/zouyx/agollo/v2@v2.2.4/app_config.go:165 +0xbd

goroutine 43 [runnable]:
github.com/zouyx/agollo/v2.updateApolloConfig(0xc000250720, 0x0)
	F:/code/pkg/mod/github.com/zouyx/agollo/v2@v2.2.4/repository.go:226
created by github.com/zouyx/agollo/v2.initApolloConfigCache.func1.1
	F:/code/pkg/mod/github.com/zouyx/agollo/v2@v2.2.4/app_config.go:165 +0xbd

goroutine 44 [runnable]:
github.com/zouyx/agollo/v2.updateApolloConfig(0xc000250780, 0x0)
	F:/code/pkg/mod/github.com/zouyx/agollo/v2@v2.2.4/repository.go:226
created by github.com/zouyx/agollo/v2.initApolloConfigCache.func1.1
	F:/code/pkg/mod/github.com/zouyx/agollo/v2@v2.2.4/app_config.go:165 +0xbd

goroutine 45 [runnable]:
github.com/zouyx/agollo/v2.updateApolloConfig(0xc0002507e0, 0x0)
	F:/code/pkg/mod/github.com/zouyx/agollo/v2@v2.2.4/repository.go:226
created by github.com/zouyx/agollo/v2.initApolloConfigCache.func1.1
	F:/code/pkg/mod/github.com/zouyx/agollo/v2@v2.2.4/app_config.go:165 +0xbd

goroutine 46 [runnable]:
github.com/zouyx/agollo/v2.updateApolloConfig(0xc000250840, 0x0)
	F:/code/pkg/mod/github.com/zouyx/agollo/v2@v2.2.4/repository.go:226
created by github.com/zouyx/agollo/v2.initApolloConfigCache.func1.1
	F:/code/pkg/mod/github.com/zouyx/agollo/v2@v2.2.4/app_config.go:165 +0xbd

goroutine 47 [runnable]:
github.com/zouyx/agollo/v2.updateApolloConfig(0xc0002508a0, 0x0)
	F:/code/pkg/mod/github.com/zouyx/agollo/v2@v2.2.4/repository.go:226
created by github.com/zouyx/agollo/v2.initApolloConfigCache.func1.1
	F:/code/pkg/mod/github.com/zouyx/agollo/v2@v2.2.4/app_config.go:165 +0xbd

goroutine 48 [runnable]:
github.com/zouyx/agollo/v2.updateApolloConfig(0xc000250900, 0x0)
	F:/code/pkg/mod/github.com/zouyx/agollo/v2@v2.2.4/repository.go:226
created by github.com/zouyx/agollo/v2.initApolloConfigCache.func1.1
	F:/code/pkg/mod/github.com/zouyx/agollo/v2@v2.2.4/app_config.go:165 +0xbd

Process finished with exit code 2
```

**Comment by qiluge** [comment]
稍微看了下，你把map做全局变量很容易出问题的，repository.go#L42 apolloConfigCache

**Comment by zouyx** [comment]
@qiluge 好，我看看，谢谢你，尽量今天改一版给你们

**Comment by zouyx** [comment]
@qiluge @lenghan1991 我知道什么问题了，之前这个[cache](https://github.com/zouyx/agollo/blob/4b8bf8dd13f405d1c4041c34c7cba3d2c4f893ea/repository.go#L42)因为只有定时程序在写，所以没问题，之前两个版本我加了个运行时同步config server的信息，所以可能会产生并发问题。
